version: 2.1
orbs:
  cypress: cypress-io/cypress@3

jobs:
  build:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - cypress/run:
          install-browsers: true
          start-command: 'npm run start'
          cypress-command: 'npx cypress run --parallel --record --group all tests --browser chrome'
          parallelism: 3